---
extends:
  - airbnb
  - prettier

plugins:
  - react
  - jsx-a11y
  - import
  - filenames
  - prettier

rules:
  filenames/match-regex:
    - 2
    - "^[a-z-\\.]+$"
  react/jsx-filename-extension:
    - 0
  no-console:
    - 0
  jsx-a11y/click-events-have-key-events:
    - 0
  jsx-a11y/no-noninteractive-element-interactions:
    - 0

env:
  browser: true
