export const GET_USER_LOCATION = 'GET_USER_LOCATION';
export const RECEIVE_USER_LOCATION = 'RECEIVE_USER_LOCATION';

export const GET_POSTS = 'GET_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';

export const GET_VK_POSTS = 'GET_VK_POSTS';
export const RECEIVE_VK_POSTS = 'RECEIVE_VK_POSTS';

export const GET_EVENTDER_POSTS = 'GET_EVENTDER_POSTS';
export const RECEIVE_EVENTDER_POSTS = 'RECEIVE_EVENTDER_POSTS';

export const ERROR = 'ERROR';
export const CHANGE_CURRENT_POST_DATA = 'CHANGE_CURRENT_POST_DATA';

export const PUBLISH_USER_FILE = 'PUBLISH_USER_FILE';
export const SUCCESS_PUBLISH_USER_FILE = 'SUCCESS_PUBLISH_USER_FILE';
export const ERROR_PUBLISH_USER_FILE = 'ERROR_PUBLISH_USER_FILE';

export const LOADING = 'LOADING';

export const SET_USER_DATA = 'SET_USER_DATA';

export const ADD_LIKE = 'ADD_LIKE';
export const REMOVE_LIKE = 'REMOVE_LIKE';

export const CHANGE_VIEWPORT = 'CHANGE_VIEWPORT';
export const TOGGLE_POST_PREVIEW_VISIBILITY = 'TOGGLE_POST_PREVIEW_VISIBILITY';
export const SET_MOBILE_DEVICE = 'SET_MOBILE_DEVICE';
