export const GET_USER_LOCATION = 'GET_USER_LOCATION';
export const RECEIVE_USER_LOCATION = 'RECEIVE_USER_LOCATION';

export const GET_POSTS = 'GET_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';

export const ERROR = 'ERROR';
export const CHANGE_CURRENT_POST_DATA = 'CHANGE_CURRENT_POST_DATA';
