export const GET_USER_LOCATION = 'GET_USER_LOCATION';
export const RECEIVE_USER_LOCATION = 'RECEIVE_USER_LOCATION';

export const GET_POSTS = 'GET_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';

export const GET_EVENTDER_POSTS = 'GET_EVENTDER_POSTS';
export const RECEIVE_EVENTDER_POSTS = 'RECEIVE_EVENTDER_POSTS';

export const ERROR = 'ERROR';
export const CHANGE_CURRENT_POST_DATA = 'CHANGE_CURRENT_POST_DATA';

export const PUBLISH_USER_FILE = 'PUBLISH_USER_FILE';
export const SUCCESS_PUBLISH_USER_FILE = 'SUCCESS_PUBLISH_USER_FILE';
export const ERROR_PUBLISH_USER_FILE = 'ERROR_PUBLISH_USER_FILE';

export const LOADING = 'LOADING';
