service: save-user-file

frameworkVersion: ">=1.1.0"

custom:
  bucket: eventder

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:s3:::${self:custom.bucket}/*"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  save:
    handler: handler.save
    environment:
      BUCKET: ${self:custom.bucket}

  create:
    handler: files/create.create
    events:
      - http:
          path: files
          method: post
          cors: true

  list:
    handler: files/list.list
    events:
      - http:
          path: files
          method: get
          cors: true

  get:
    handler: files/get.get
    events:
      - http:
          path: files/{id}
          method: get
          cors: true

  update:
    handler: files/update.update
    events:
      - http:
          path: files/{id}
          method: put
          cors: true

  delete:
    handler: files/delete.delete
    events:
      - http:
          path: files/{id}
          method: delete
          cors: true

resources:
  Resources:
    FilesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}